import './globals.css'

import { NavigationDesktop } from '@/components/NavigationBar/navigation-desktop'
import { GeistSans } from 'geist/font/sans'
import { Providers } from './providers'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={GeistSans.className} suppressHydrationWarning>
        <Providers>
          <NavigationDesktop />

          {children}
        </Providers>
      </body>
    </html>
  )
}
