import './globals.css'

import type { Metadata } from 'next'
import { Providers } from './providers'
import { GeistSans } from 'geist/font/sans'
import { Toaster } from '@/components/ui/sonner'
import NavigationDesktop from '@/components/NavigationBar/navigation-desktop'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang='en' suppressHydrationWarning>
        <body className={GeistSans.className} suppressHydrationWarning>
          <NavigationDesktop />

          {children}
          <Toaster />
        </body>
      </html>
    </Providers>
  )
}
