import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';

const TermsOfUseMatters = [
  {
    title: 'Acceptance of Terms',
    content:
      'By purchasing and using the code template provided by Shipi.fyi, you agree to be bound by these terms and conditions.'
  },
  {
    title: 'Product Description',
    content:
      "Shipi.fyi's aim is to offer a ready-to-use headless Shopify storefront boilerplate for Javascript/Typescript web applications designed to ease the workload of individual and freelance developers."
  },
  {
    title: 'Usage Rights',
    content:
      "Unlimited Access Software License with Termination Rights. The Shipi.fyi Software License facilitates the acquisition of ShipFast software through a single purchase, granting users unrestricted and perpetual access to its comprehensive functionalities. Tailored for independent creators, entrepreneurs, and small businesses, Shipi.fyi empowers users to create compelling Headless Shopify storefront pages. This license entails a straightforward and flexible arrangement, exempting users from recurring fees or subscriptions. However, it is important to acknowledge that the licensor retains the right to terminate the license without conditions or prerequisites. This termination provision enables the licensor to exercise control over software distribution and utilization. Opting for the Shipi.fyi Software License enables users to enjoy the benefits of the software while recognizing the licensor's unrestricted termination rights, which provide adaptability and address potential unforeseen circumstances. Shipi.fyi will not be held responsible for any consequences resulting from the use of the template."
  },
  {
    title: 'Payments and Refunds',
    content:
      'All sales are final. Due to the nature of digital products, Shipi.fyi cannot be refunded once access to the code is granted.'
  },
  {
    title: 'Disclaimer of Warranties',
    content:
      'Shipi.fyi provides the code template on an "as-is" basis without any warranties, express or implied. We do not warrant that the template will meet your requirements or that its operation will be uninterrupted or error-free. We disclaim all warranties to the fullest extent permissible by law.'
  },
  {
    title: 'Limitation of Liability',
    content:
      'To the maximum extent permitted by law, Shipi.fyi will not be liable for any indirect, special, incidental, or consequential damages arising out of or in connection with the use of or inability to use the template. Our total liability to you for any claim arising out of or relating to these terms or the template will not exceed the amount you paid for the template.'
  },
  {
    title: 'Responsibilities',
    content:
      'Shipi.fyi is not responsible for any content or data generated by the user through the use of the code template.'
  },
  {
    title: 'Changes to the Terms',
    content:
      'We reserve the right to modify these terms at any time. Changes will be posted on our website and will become effective immediately upon posting. Your continued use of the template after changes are posted constitutes your acceptance of the new terms.'
  }
];

export default function TermsOfService() {
  return (
    <div className="w-full px-10 md:px-0 md:w-[600px] mx-auto py-10">
      <Link href="/" className='flex items-center gap-2 mb-10 max-w-min hover:scale-105 transition-transform duration-300'>
        <ArrowLeft size={14} /> Back
      </Link>
      <h1 className="text-3xl font-bold mb-10">Terms of Service</h1>
      <ul className="flex flex-col gap-5 ml-5">
        {TermsOfUseMatters.map((matter, index) => (
          <div key={index}>
            <li className="list-decimal font-semibold mb-3">{matter.title}</li>
            <p className='text-neutral-400'>{matter.content}</p>
          </div>
        ))}
      </ul>
    </div>
  );
}